# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba7c60d397ffe502c317ff6af2c40985a90245c4afe6640ffc257c28cd628e60f27547cc2652eb02c81e80e9120966a7622461fcdb7919605b51709c13ffa726

test:
  secret_key_base: e455e8bc41f74e3bc760dd9effa922b09fbf9537f83ef234b3bdc392a631bf06c5c387b6f1f9a8df687fe8574d39b1467d2b8ad576fb3ede3931dc007ff25faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
